/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;
import modelo.Usuario;
import controlador.ControladorUsuario;
import javax.swing.JOptionPane;
/**
 *
 * @author erick
 */
public class FRMEditarUsuario extends javax.swing.JInternalFrame {

    private Usuario usuario;
    /**
     * Creates new form FRMEditarUsuario
     */
    public FRMEditarUsuario(Usuario usuario) {
        initComponents();
        
        this.usuario = usuario;

        TXTEditarNombre.setText(usuario.getNombre());
        TXTEditarTelefono.setText(usuario.getTelefono());
        TXTEditarCorreo.setText(usuario.getCorreo());

        PWEditarContraseña.setText(usuario.getContraseña());
        PWEditarCofirmarContraseña.setText(usuario.getContraseña());

        CBOEditarRol.setSelectedItem(usuario.getRol());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new modelo.FondoPanel();
        TXTEditarTelefono = new javax.swing.JTextField();
        TXTEditarCorreo = new javax.swing.JTextField();
        PWEditarContraseña = new javax.swing.JPasswordField();
        LBLEditarNombre = new javax.swing.JLabel();
        PWEditarCofirmarContraseña = new javax.swing.JPasswordField();
        LBLEditarTelefono = new javax.swing.JLabel();
        CBOEditarRol = new javax.swing.JComboBox<>();
        LBLEditarCorreo = new javax.swing.JLabel();
        LBLEditarContraseña = new javax.swing.JLabel();
        LBLEditarConfirmarContraseña = new javax.swing.JLabel();
        LBLEditarRol = new javax.swing.JLabel();
        TXTEditarNombre = new javax.swing.JTextField();
        BTNEditar = new javax.swing.JButton();

        LBLEditarNombre.setText("Nombre");

        LBLEditarTelefono.setText("Telefono");

        CBOEditarRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMIN", "CLIENTE" }));

        LBLEditarCorreo.setText("Correo");

        LBLEditarContraseña.setText("Contraseña");

        LBLEditarConfirmarContraseña.setText("Confirmar Contrseña");

        LBLEditarRol.setText("Rol");

        BTNEditar.setText("Editar");
        BTNEditar.addActionListener(this::BTNEditarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBLEditarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBLEditarTelefono)
                            .addComponent(LBLEditarCorreo)
                            .addComponent(LBLEditarContraseña)
                            .addComponent(LBLEditarConfirmarContraseña)
                            .addComponent(LBLEditarRol))
                        .addGap(101, 101, 101)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(PWEditarCofirmarContraseña, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PWEditarContraseña, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTEditarCorreo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTEditarTelefono, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTEditarNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CBOEditarRol, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(BTNEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLEditarNombre)
                    .addComponent(TXTEditarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLEditarTelefono)
                    .addComponent(TXTEditarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLEditarCorreo)
                    .addComponent(TXTEditarCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLEditarContraseña)
                    .addComponent(PWEditarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLEditarConfirmarContraseña)
                    .addComponent(PWEditarCofirmarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLEditarRol)
                    .addComponent(CBOEditarRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(BTNEditar)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEditarActionPerformed
        // TODO add your handling code here:
        String contraseña = String.valueOf(PWEditarContraseña.getPassword());
        String confirmar = String.valueOf(PWEditarCofirmarContraseña.getPassword());

        if (!contraseña.equals(confirmar)) {
            JOptionPane.showMessageDialog(this,
                    "Las contraseñas no coinciden");
            return;
        }
        if (TXTEditarNombre.getText().trim().isEmpty()
                || TXTEditarTelefono.getText().trim().isEmpty()
                || TXTEditarCorreo.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(this,
                    "Debe completar todos los campos.");
            return;
        }

        usuario.setNombre(TXTEditarNombre.getText());
        usuario.setTelefono(TXTEditarTelefono.getText());
        usuario.setCorreo(TXTEditarCorreo.getText());
        usuario.setContraseña(contraseña);
        usuario.setRol(CBOEditarRol.getSelectedItem().toString());

        ControladorUsuario controlador = new ControladorUsuario();
        
        if (controlador.actualizarUsuario(usuario)) {
            JOptionPane.showMessageDialog(this,
                    "Usuario actualizado correctamente");
            dispose();
        } else {
            JOptionPane.showMessageDialog(this,
                    "No se pudo actualizar el usuario");
        }
    }//GEN-LAST:event_BTNEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNEditar;
    private javax.swing.JComboBox<String> CBOEditarRol;
    private javax.swing.JLabel LBLEditarConfirmarContraseña;
    private javax.swing.JLabel LBLEditarContraseña;
    private javax.swing.JLabel LBLEditarCorreo;
    private javax.swing.JLabel LBLEditarNombre;
    private javax.swing.JLabel LBLEditarRol;
    private javax.swing.JLabel LBLEditarTelefono;
    private javax.swing.JPasswordField PWEditarCofirmarContraseña;
    private javax.swing.JPasswordField PWEditarContraseña;
    private javax.swing.JTextField TXTEditarCorreo;
    private javax.swing.JTextField TXTEditarNombre;
    private javax.swing.JTextField TXTEditarTelefono;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
