/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import controlador.ControladorHorario;
import controlador.ControladorEntrenador;
import modelo.Entrenador;
import modelo.HorariosEntrenadores;
/**
 *
 * @author erick
 */
public class FRMEditarHorario extends javax.swing.JInternalFrame {

    private HorariosEntrenadores horario;
    
    private void cargarDias() {

        CBODiaEditarHorario.removeAllItems();

        CBODiaEditarHorario.addItem("Lunes");
        CBODiaEditarHorario.addItem("Martes");
        CBODiaEditarHorario.addItem("Miércoles");
        CBODiaEditarHorario.addItem("Jueves");
        CBODiaEditarHorario.addItem("Viernes");
        CBODiaEditarHorario.addItem("Sábado");
        CBODiaEditarHorario.addItem("Domingo");

    }
    
    private void cargarEntrenadores() {

        CBOEnntrenadorHorario.removeAllItems();

        ControladorEntrenador controlador = new ControladorEntrenador();

        for (Entrenador e : controlador.listarEntrenadores()) {
            CBOEnntrenadorHorario.addItem(e.getNombre());
        }

    }
    /**
     * Creates new form FRMEditarHorario
     */
    public FRMEditarHorario(HorariosEntrenadores horario) {
        initComponents();
        this.horario = horario;

        cargarDias();
        cargarEntrenadores();

        cargarDatos();
    }
    
    private void cargarDatos() {

        CBOEnntrenadorHorario.setSelectedItem(horario.getNombreEntrenador());
        CBODiaEditarHorario.setSelectedItem(horario.getDia());
        TXTEditarHoraInicio.setText(horario.getHoraInicio());
        TXTEditarHorarioFin.setText(horario.getHoraFin());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CBOEnntrenadorHorario = new javax.swing.JComboBox<>();
        CBODiaEditarHorario = new javax.swing.JComboBox<>();
        TXTEditarHoraInicio = new javax.swing.JTextField();
        TXTEditarHorarioFin = new javax.swing.JTextField();
        BTNEditarHorario = new javax.swing.JButton();
        BTNEditarCancelar = new javax.swing.JButton();

        jLabel1.setText("Entrenador");

        jLabel2.setText("Dia");

        jLabel3.setText("Hora Inicio");

        jLabel4.setText("Hora Fin");

        CBOEnntrenadorHorario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CBODiaEditarHorario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        BTNEditarHorario.setText("Editar");
        BTNEditarHorario.addActionListener(this::BTNEditarHorarioActionPerformed);

        BTNEditarCancelar.setText("Cancelar");
        BTNEditarCancelar.addActionListener(this::BTNEditarCancelarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CBODiaEditarHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(92, 92, 92)
                            .addComponent(CBOEnntrenadorHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(BTNEditarCancelar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTNEditarHorario))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TXTEditarHorarioFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(94, 94, 94)
                            .addComponent(TXTEditarHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(CBOEnntrenadorHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addComponent(CBODiaEditarHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TXTEditarHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TXTEditarHorarioFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNEditarHorario)
                    .addComponent(BTNEditarCancelar))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNEditarHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEditarHorarioActionPerformed
        // TODO add your handling code here:
        ControladorHorario controlador = new ControladorHorario();

        // Obtener el entrenador seleccionado
        String nombre = CBOEnntrenadorHorario.getSelectedItem().toString();

        Entrenador entrenador = controlador.buscarPorNombre(nombre);

        if (entrenador == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "No se encontró el entrenador.");
            return;
        }

        // Actualizar el objeto horario
        horario.setIdEntrenador(entrenador.getIdEntrenador());
        horario.setNombreEntrenador(entrenador.getNombre());
        horario.setDia(CBODiaEditarHorario.getSelectedItem().toString());
        horario.setHoraInicio(TXTEditarHoraInicio.getText());
        horario.setHoraFin(TXTEditarHorarioFin.getText());

        if (controlador.actualizarHorario(horario)) {

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Horario actualizado correctamente.");

            dispose();

        } else {

            javax.swing.JOptionPane.showMessageDialog(this,
                    "No se pudo actualizar el horario.");
        }
    }//GEN-LAST:event_BTNEditarHorarioActionPerformed

    private void BTNEditarCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEditarCancelarActionPerformed
        // TODO add your handling code here:
            dispose();
    }//GEN-LAST:event_BTNEditarCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNEditarCancelar;
    private javax.swing.JButton BTNEditarHorario;
    private javax.swing.JComboBox<String> CBODiaEditarHorario;
    private javax.swing.JComboBox<String> CBOEnntrenadorHorario;
    private javax.swing.JTextField TXTEditarHoraInicio;
    private javax.swing.JTextField TXTEditarHorarioFin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
