/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;
import controlador.ControladorMembresia;
import javax.swing.JOptionPane;
import modelo.Membresia;
/**
 *
 * @author erick
 */
public class FRMEditarMembresia extends javax.swing.JInternalFrame {

    private Membresia membresia;
    /**
     * Creates new form FRMEditarMembresia
     */
    public FRMEditarMembresia(Membresia membresia) {
        initComponents();
        this.membresia = membresia;

        TXTNombreEdiMem.setText(membresia.getNombre());
        TXTPrecioEdiMem.setText(String.valueOf(membresia.getPrecio()));
        TXTDuracionEdiMem.setText(String.valueOf(membresia.getDuracion()));
        TXADescripcionEdiMem.setText(membresia.getDescripcion());

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TXTNombreEdiMem = new javax.swing.JTextField();
        TXTPrecioEdiMem = new javax.swing.JTextField();
        TXTDuracionEdiMem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TXADescripcionEdiMem = new javax.swing.JTextArea();
        BTNGuardarEdiMem = new javax.swing.JButton();

        jLabel1.setText("Nombre");

        jLabel2.setText("Precio");

        jLabel3.setText("Duración");

        jLabel4.setText("Descripción");

        TXADescripcionEdiMem.setColumns(20);
        TXADescripcionEdiMem.setRows(5);
        jScrollPane1.setViewportView(TXADescripcionEdiMem);

        BTNGuardarEdiMem.setText("Editar");
        BTNGuardarEdiMem.addActionListener(this::BTNGuardarEdiMemActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TXTDuracionEdiMem, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TXTNombreEdiMem, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(TXTPrecioEdiMem))
                        .addGap(162, 162, 162)
                        .addComponent(BTNGuardarEdiMem)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTNombreEdiMem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNGuardarEdiMem)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTPrecioEdiMem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(TXTDuracionEdiMem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNGuardarEdiMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNGuardarEdiMemActionPerformed
        // TODO add your handling code here:
        if (TXTNombreEdiMem.getText().trim().isEmpty()
            || TXTPrecioEdiMem.getText().trim().isEmpty()
            || TXTDuracionEdiMem.getText().trim().isEmpty()
            || TXADescripcionEdiMem.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(this,
                    "Complete todos los campos.");
            return;
        }

        try {

            membresia.setNombre(TXTNombreEdiMem.getText());
            membresia.setPrecio(Double.parseDouble(TXTPrecioEdiMem.getText()));
            membresia.setDuracion(Integer.parseInt(TXTDuracionEdiMem.getText()));
            membresia.setDescripcion(TXADescripcionEdiMem.getText());

            ControladorMembresia controlador = new ControladorMembresia();

            if (controlador.actualizarMembresia(membresia)) {

                JOptionPane.showMessageDialog(this,
                        "Membresía actualizada correctamente.");

                dispose();

            } else {

                JOptionPane.showMessageDialog(this,
                        "No se pudo actualizar la membresía.");
            }

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(this,
                    "Precio y duración deben ser números.");

        }
    }//GEN-LAST:event_BTNGuardarEdiMemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNGuardarEdiMem;
    private javax.swing.JTextArea TXADescripcionEdiMem;
    private javax.swing.JTextField TXTDuracionEdiMem;
    private javax.swing.JTextField TXTNombreEdiMem;
    private javax.swing.JTextField TXTPrecioEdiMem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
