/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import controlador.ControladorUsuario;
import javax.swing.JOptionPane;
import modelo.Usuario;

/**
 *
 * @author erick
 */
public class FRMRegistrarse extends javax.swing.JInternalFrame {

    /**
     * Creates new form FRMRegistrarse
     */
    public FRMRegistrarse() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBLNombre = new javax.swing.JLabel();
        LBLTelefono = new javax.swing.JLabel();
        LBLCorreo = new javax.swing.JLabel();
        LBLContraseña = new javax.swing.JLabel();
        LBLConfirmarContraseña = new javax.swing.JLabel();
        BTNCrearCuenta = new javax.swing.JButton();
        TXTNombre = new javax.swing.JTextField();
        TXTTelefono = new javax.swing.JTextField();
        TXTCorreo = new javax.swing.JTextField();
        PWContraseña = new javax.swing.JPasswordField();
        PWConfirmarContraseña = new javax.swing.JPasswordField();

        LBLNombre.setText("Nombre");

        LBLTelefono.setText("Telefono");

        LBLCorreo.setText("Correo");

        LBLContraseña.setText("Contraseña");

        LBLConfirmarContraseña.setText("Confirmar Contraseña");

        BTNCrearCuenta.setText("Crear Cuenta");
        BTNCrearCuenta.addActionListener(this::BTNCrearCuentaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBLNombre)
                            .addComponent(LBLTelefono)
                            .addComponent(LBLCorreo)
                            .addComponent(LBLContraseña)
                            .addComponent(LBLConfirmarContraseña))
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TXTNombre)
                                .addComponent(TXTTelefono)
                                .addComponent(TXTCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                .addComponent(PWContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(PWConfirmarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(BTNCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLNombre)
                    .addComponent(TXTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLTelefono)
                    .addComponent(TXTTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLCorreo)
                    .addComponent(TXTCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLContraseña)
                    .addComponent(PWContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLConfirmarContraseña)
                    .addComponent(PWConfirmarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BTNCrearCuenta)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCrearCuentaActionPerformed
        // TODO add your handling code here:
        String nombre = TXTNombre.getText();
        String telefono = TXTTelefono.getText();
        String correo = TXTCorreo.getText();
        
        String contraseña = String.valueOf(PWContraseña.getPassword());
        String confirmar = String.valueOf(PWConfirmarContraseña.getPassword());
        
        if(nombre.isEmpty() || telefono.isEmpty() || correo.isEmpty() || contraseña.isEmpty() || confirmar.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Debe completar todos los campos");
            return;
        }
        if(!contraseña.equals(confirmar)){
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Las contraseñas no coinciden");
            return;
        }
        Usuario usuario = new Usuario();
        
        usuario.setNombre(nombre);
        usuario.setTelefono(telefono);
        usuario.setCorreo(correo);
        usuario.setContraseña(contraseña);
        
        ControladorUsuario controlador = new ControladorUsuario();
        
        if(controlador.guardarUsuario(usuario)){
            
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Cuenta creada correctamente");
            
                TXTNombre.setText("");
                TXTTelefono.setText("");
                TXTCorreo.setText("");
                PWContraseña.setText("");
                PWConfirmarContraseña.setText("");
        }else{
            JOptionPane.showMessageDialog(this,
                    "Error al crear la cuenta");
            
        }
        
    }//GEN-LAST:event_BTNCrearCuentaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCrearCuenta;
    private javax.swing.JLabel LBLConfirmarContraseña;
    private javax.swing.JLabel LBLContraseña;
    private javax.swing.JLabel LBLCorreo;
    private javax.swing.JLabel LBLNombre;
    private javax.swing.JLabel LBLTelefono;
    private javax.swing.JPasswordField PWConfirmarContraseña;
    private javax.swing.JPasswordField PWContraseña;
    private javax.swing.JTextField TXTCorreo;
    private javax.swing.JTextField TXTNombre;
    private javax.swing.JTextField TXTTelefono;
    // End of variables declaration//GEN-END:variables
}
