/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import img.FondoEscritorio;
import controlador.ControladorUsuario;
import javax.swing.JOptionPane;
import modelo.Usuario;

/**
 *
 * @author erick
 */
public class FRMRegistrarse extends javax.swing.JInternalFrame {

    private Usuario usuarioEditar;
    private int idUsuario = 0;
    /**
     * Creates new form FRMRegistrarse
     */
    public FRMRegistrarse() {
        initComponents();
        

        
    }
    
    public FRMRegistrarse(Usuario usuario) {
    initComponents();

    usuarioEditar = usuario;
    TXTNombre.setText(usuario.getNombre());
    TXTTelefono.setText(usuario.getTelefono());
    TXTCorreo.setText(usuario.getCorreo());
    PWContraseña.setText(usuario.getContraseña());
    PWConfirmarContraseña.setText(usuario.getContraseña());

    idUsuario = usuario.getIdUsuario();
    BTNCrearCuenta.setText("Actualizar");

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EscritorioRegistrarse = new FondoEscritorio();
        TXTTelefono = new javax.swing.JTextField();
        TXTCorreo = new javax.swing.JTextField();
        PWContraseña = new javax.swing.JPasswordField();
        PWConfirmarContraseña = new javax.swing.JPasswordField();
        LBLNombre = new javax.swing.JLabel();
        LBLTelefono = new javax.swing.JLabel();
        LBLCorreo = new javax.swing.JLabel();
        LBLContraseña = new javax.swing.JLabel();
        LBLConfirmarContraseña = new javax.swing.JLabel();
        BTNCrearCuenta = new javax.swing.JButton();
        TXTNombre = new javax.swing.JTextField();

        setClosable(true);

        LBLNombre.setFont(new java.awt.Font("Courier 10 Pitch", 1, 13)); // NOI18N
        LBLNombre.setForeground(new java.awt.Color(255, 255, 255));
        LBLNombre.setText("Nombre");

        LBLTelefono.setFont(new java.awt.Font("Courier 10 Pitch", 1, 13)); // NOI18N
        LBLTelefono.setForeground(new java.awt.Color(255, 255, 255));
        LBLTelefono.setText("Telefono");

        LBLCorreo.setFont(new java.awt.Font("Courier 10 Pitch", 1, 13)); // NOI18N
        LBLCorreo.setForeground(new java.awt.Color(255, 255, 255));
        LBLCorreo.setText("Correo");

        LBLContraseña.setFont(new java.awt.Font("Courier 10 Pitch", 1, 13)); // NOI18N
        LBLContraseña.setForeground(new java.awt.Color(255, 255, 255));
        LBLContraseña.setText("Contraseña");

        LBLConfirmarContraseña.setFont(new java.awt.Font("Courier 10 Pitch", 1, 13)); // NOI18N
        LBLConfirmarContraseña.setForeground(new java.awt.Color(255, 255, 255));
        LBLConfirmarContraseña.setText("Confirmar Contraseña");

        BTNCrearCuenta.setText("Crear Cuenta");
        BTNCrearCuenta.addActionListener(this::BTNCrearCuentaActionPerformed);

        EscritorioRegistrarse.setLayer(TXTTelefono, javax.swing.JLayeredPane.DEFAULT_LAYER);
        EscritorioRegistrarse.setLayer(TXTCorreo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        EscritorioRegistrarse.setLayer(PWContraseña, javax.swing.JLayeredPane.DEFAULT_LAYER);
        EscritorioRegistrarse.setLayer(PWConfirmarContraseña, javax.swing.JLayeredPane.DEFAULT_LAYER);
        EscritorioRegistrarse.setLayer(LBLNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        EscritorioRegistrarse.setLayer(LBLTelefono, javax.swing.JLayeredPane.DEFAULT_LAYER);
        EscritorioRegistrarse.setLayer(LBLCorreo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        EscritorioRegistrarse.setLayer(LBLContraseña, javax.swing.JLayeredPane.DEFAULT_LAYER);
        EscritorioRegistrarse.setLayer(LBLConfirmarContraseña, javax.swing.JLayeredPane.DEFAULT_LAYER);
        EscritorioRegistrarse.setLayer(BTNCrearCuenta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        EscritorioRegistrarse.setLayer(TXTNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout EscritorioRegistrarseLayout = new javax.swing.GroupLayout(EscritorioRegistrarse);
        EscritorioRegistrarse.setLayout(EscritorioRegistrarseLayout);
        EscritorioRegistrarseLayout.setHorizontalGroup(
            EscritorioRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EscritorioRegistrarseLayout.createSequentialGroup()
                .addGroup(EscritorioRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EscritorioRegistrarseLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(EscritorioRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBLCorreo)
                            .addComponent(LBLContraseña)
                            .addComponent(LBLConfirmarContraseña)
                            .addComponent(LBLTelefono)
                            .addComponent(LBLNombre))
                        .addGap(77, 77, 77)
                        .addGroup(EscritorioRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EscritorioRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TXTNombre)
                                .addComponent(TXTTelefono)
                                .addComponent(TXTCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(PWContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(PWConfirmarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(EscritorioRegistrarseLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(BTNCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EscritorioRegistrarseLayout.setVerticalGroup(
            EscritorioRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EscritorioRegistrarseLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(EscritorioRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBLNombre))
                .addGap(18, 18, 18)
                .addGroup(EscritorioRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLTelefono)
                    .addComponent(TXTTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EscritorioRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLCorreo)
                    .addComponent(TXTCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EscritorioRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLContraseña)
                    .addComponent(PWContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EscritorioRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLConfirmarContraseña)
                    .addComponent(PWConfirmarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(BTNCrearCuenta)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EscritorioRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(EscritorioRegistrarse)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCrearCuentaActionPerformed
        // TODO add your handling code here:
        String nombre = TXTNombre.getText();
        String telefono = TXTTelefono.getText();
        String correo = TXTCorreo.getText();
        
        String contraseña = String.valueOf(PWContraseña.getPassword());
        String confirmar = String.valueOf(PWConfirmarContraseña.getPassword());
        
        if(nombre.isEmpty() || telefono.isEmpty() || correo.isEmpty() || contraseña.isEmpty() || confirmar.isEmpty()){
            JOptionPane.showMessageDialog(this, 
                    "Debe completar todos los campos");
            return;
        }
        if(!contraseña.equals(confirmar)){
            JOptionPane.showMessageDialog(this, 
                    "Las contraseñas no coinciden");
            return;
        }
        
        Usuario usuario = new Usuario();
        
        usuario.setIdUsuario(idUsuario);
        usuario.setNombre(nombre);
        usuario.setTelefono(telefono);
        usuario.setCorreo(correo);
        usuario.setContraseña(contraseña);
        
        if(usuarioEditar != null){
            usuario.setRol(usuarioEditar.getRol());
        }
        
        ControladorUsuario controlador = new ControladorUsuario();
        
        boolean resultado;
        
        if(idUsuario == 0){
            resultado = controlador.guardarUsuario(usuario);
        }else{
            resultado = controlador.actualizarUsuario(usuario);
        }
        
        if(resultado){
            JOptionPane.showMessageDialog(this,
                idUsuario == 0 ?
                "Cuenta creada correctamente" :
                "Usuario actualizado correctamente");
            dispose();

        }else{

            JOptionPane.showMessageDialog(this,
                    "Error al guardar la información");
            
        }
    }//GEN-LAST:event_BTNCrearCuentaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCrearCuenta;
    private javax.swing.JDesktopPane EscritorioRegistrarse;
    private javax.swing.JLabel LBLConfirmarContraseña;
    private javax.swing.JLabel LBLContraseña;
    private javax.swing.JLabel LBLCorreo;
    private javax.swing.JLabel LBLNombre;
    private javax.swing.JLabel LBLTelefono;
    private javax.swing.JPasswordField PWConfirmarContraseña;
    private javax.swing.JPasswordField PWContraseña;
    private javax.swing.JTextField TXTCorreo;
    private javax.swing.JTextField TXTNombre;
    private javax.swing.JTextField TXTTelefono;
    // End of variables declaration//GEN-END:variables
}
