/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import controlador.ControladorEntrenador;
import controlador.ControladorHorario;
import javax.swing.JOptionPane;
import modelo.Entrenador;
import modelo.HorariosEntrenadores;

/**
 *
 * @author erick
 */
public class FRMRegistrarHorario extends javax.swing.JInternalFrame {

    private void cargarDias() {

        CBODiaHora.removeAllItems();

        CBODiaHora.addItem("Lunes");
        CBODiaHora.addItem("Martes");
        CBODiaHora.addItem("Miércoles");
        CBODiaHora.addItem("Jueves");
        CBODiaHora.addItem("Viernes");
        CBODiaHora.addItem("Sábado");
        CBODiaHora.addItem("Domingo");

    }
    private void cargarEntrenadores() {

        CBOEntrenadorHora.removeAllItems();

        ControladorEntrenador controlador = new ControladorEntrenador();

        for (Entrenador e : controlador.listarEntrenadores()) {

            CBOEntrenadorHora.addItem(e.getNombre());
        }
    }
    /**
     * Creates new form FRMRegistrarHorario
     */
    public FRMRegistrarHorario() {
        initComponents();
        cargarDias();
        cargarEntrenadores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BTNRegistrarHorario = new javax.swing.JButton();
        CBOEntrenadorHora = new javax.swing.JComboBox<>();
        CBODiaHora = new javax.swing.JComboBox<>();
        TXTHoraInicio = new javax.swing.JTextField();
        TXTHoraFin = new javax.swing.JTextField();
        BTNCancelar = new javax.swing.JButton();

        jLabel1.setText("Entrenador");

        jLabel2.setText("Dia");

        jLabel3.setText("Hora Inicio");

        jLabel4.setText("Hora Fin");

        BTNRegistrarHorario.setText("CREAR");
        BTNRegistrarHorario.addActionListener(this::BTNRegistrarHorarioActionPerformed);

        CBOEntrenadorHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 3", "Item 4" }));

        CBODiaHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 3", "Item 4" }));

        BTNCancelar.setText("Cancelar");
        BTNCancelar.addActionListener(this::BTNCancelarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(14, 14, 14))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(2, 2, 2))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(44, 44, 44))
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(BTNCancelar))
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CBOEntrenadorHora, javax.swing.GroupLayout.Alignment.TRAILING, 0, 82, Short.MAX_VALUE)
                    .addComponent(CBODiaHora, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TXTHoraInicio)
                    .addComponent(BTNRegistrarHorario)
                    .addComponent(TXTHoraFin))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CBOEntrenadorHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CBODiaHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TXTHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(TXTHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNRegistrarHorario)
                    .addComponent(BTNCancelar))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNRegistrarHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNRegistrarHorarioActionPerformed
        // TODO add your handling code here:
        String nombreEntrenador = CBOEntrenadorHora.getSelectedItem().toString();
        String dia = CBODiaHora.getSelectedItem().toString();
        String horaInicio = TXTHoraInicio.getText();
        String horaFin = TXTHoraFin.getText();

        if(horaInicio.isEmpty() || horaFin.isEmpty()){

            JOptionPane.showMessageDialog(this,
                    "Complete todos los campos");

            return;
        }

        ControladorEntrenador controladorEntrenador = new ControladorEntrenador();

        Entrenador entrenador =
                controladorEntrenador.buscarPorNombre(nombreEntrenador);

        HorariosEntrenadores horario = new HorariosEntrenadores();

        horario.setIdEntrenador(entrenador.getIdEntrenador());
        horario.setDia(dia);
        horario.setHoraInicio(horaInicio);
        horario.setHoraFin(horaFin);

        ControladorHorario controladorHorario = new ControladorHorario();

        if(controladorHorario.registrarHorario(horario)){

            JOptionPane.showMessageDialog(this,
                    "Horario registrado correctamente");

            dispose();

        }else{

            JOptionPane.showMessageDialog(this,
                    "No se pudo registrar el horario");
        }
    }//GEN-LAST:event_BTNRegistrarHorarioActionPerformed

    private void BTNCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCancelar;
    private javax.swing.JButton BTNRegistrarHorario;
    private javax.swing.JComboBox<String> CBODiaHora;
    private javax.swing.JComboBox<String> CBOEntrenadorHora;
    private javax.swing.JTextField TXTHoraFin;
    private javax.swing.JTextField TXTHoraInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
