/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;
import modelo.PanelHorarios;
import modelo.PanelMembresias;
import modelo.PanelUsuarios;
import modelo.Usuario;
import modelo.Entrenador;
import modelo.PanelEntrenador;
/**
 *
 * @author erick
 */
public class FRMUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form FRMUsuario
     */
    public FRMUsuario(Usuario usuario) {
        initComponents();
        if(usuario.getRol().equals("ADMIN")){
            BTNUsuarios.setVisible(true);
            BNTMembresias.setVisible(true);
            BNTHorario.setVisible(true);
            BTNEntrenador.setVisible(true);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PNLBotonesMenu = new javax.swing.JPanel();
        BTNEntrenador = new javax.swing.JButton();
        BNTMembresias = new javax.swing.JButton();
        BNTHorario = new javax.swing.JButton();
        BTNUsuarios = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BTNSalir = new javax.swing.JButton();
        PNLMostrarContenido = new modelo.FondoPanel ();

        setClosable(true);

        BTNEntrenador.setText("Entrenadores");
        BTNEntrenador.addActionListener(this::BTNEntrenadorActionPerformed);

        BNTMembresias.setText("Membresias");
        BNTMembresias.addActionListener(this::BNTMembresiasActionPerformed);

        BNTHorario.setText("Horarios");
        BNTHorario.addActionListener(this::BNTHorarioActionPerformed);

        BTNUsuarios.setText("Usuarios");
        BTNUsuarios.addActionListener(this::BTNUsuariosActionPerformed);

        BTNSalir.setText("Salir");

        javax.swing.GroupLayout PNLBotonesMenuLayout = new javax.swing.GroupLayout(PNLBotonesMenu);
        PNLBotonesMenu.setLayout(PNLBotonesMenuLayout);
        PNLBotonesMenuLayout.setHorizontalGroup(
            PNLBotonesMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNLBotonesMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PNLBotonesMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BNTHorario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNEntrenador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BNTMembresias, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(BTNSalir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PNLBotonesMenuLayout.setVerticalGroup(
            PNLBotonesMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNLBotonesMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BNTMembresias, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BNTHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(BTNSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout PNLMostrarContenidoLayout = new javax.swing.GroupLayout(PNLMostrarContenido);
        PNLMostrarContenido.setLayout(PNLMostrarContenidoLayout);
        PNLMostrarContenidoLayout.setHorizontalGroup(
            PNLMostrarContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 456, Short.MAX_VALUE)
        );
        PNLMostrarContenidoLayout.setVerticalGroup(
            PNLMostrarContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PNLBotonesMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PNLMostrarContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PNLMostrarContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PNLBotonesMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BNTMembresiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNTMembresiasActionPerformed
        // TODO add your handling code here:
        PNLMostrarContenido.removeAll();

        PNLMostrarContenido.setLayout(new java.awt.BorderLayout());
        PanelMembresias panel = new PanelMembresias((javax.swing.JDesktopPane) getDesktopPane());

        panel.setSize(
            PNLMostrarContenido.getWidth(),
            PNLMostrarContenido.getHeight()
        );

        panel.setLocation(0, 0);

        PNLMostrarContenido.add(panel, java.awt.BorderLayout.CENTER);

        PNLMostrarContenido.revalidate();
        PNLMostrarContenido.repaint();
    }//GEN-LAST:event_BNTMembresiasActionPerformed

    private void BNTHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNTHorarioActionPerformed
        // TODO add your handling code here:
        PNLMostrarContenido.removeAll();

        PanelHorarios panel = 
                new PanelHorarios((javax.swing.JDesktopPane) getDesktopPane());

        PNLMostrarContenido.setLayout(new java.awt.BorderLayout());
        PNLMostrarContenido.add(panel, java.awt.BorderLayout.CENTER);

        PNLMostrarContenido.revalidate();
        PNLMostrarContenido.repaint();
    }//GEN-LAST:event_BNTHorarioActionPerformed

    private void BTNUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNUsuariosActionPerformed
        // TODO add your handling code here:
        PNLMostrarContenido.removeAll();

    PanelUsuarios panel = new PanelUsuarios((javax.swing.JDesktopPane)getDesktopPane());

    PNLMostrarContenido.setLayout(new java.awt.BorderLayout());
    PNLMostrarContenido.add(panel, java.awt.BorderLayout.CENTER);

    PNLMostrarContenido.revalidate();
    PNLMostrarContenido.repaint();
    }//GEN-LAST:event_BTNUsuariosActionPerformed

    private void BTNEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEntrenadorActionPerformed
        // TODO add your handling code here:
        PNLMostrarContenido.removeAll();

        PanelEntrenador panel =
                new PanelEntrenador((javax.swing.JDesktopPane) getDesktopPane());

        PNLMostrarContenido.setLayout(new java.awt.BorderLayout());
        PNLMostrarContenido.add(panel, java.awt.BorderLayout.CENTER);

        PNLMostrarContenido.revalidate();
        PNLMostrarContenido.repaint();
    }//GEN-LAST:event_BTNEntrenadorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BNTHorario;
    private javax.swing.JButton BNTMembresias;
    private javax.swing.JButton BTNEntrenador;
    private javax.swing.JButton BTNSalir;
    private javax.swing.JButton BTNUsuarios;
    private javax.swing.JPanel PNLBotonesMenu;
    private javax.swing.JPanel PNLMostrarContenido;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
