/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package vista;

import img.FondoEscritorio0;
import java.beans.PropertyVetoException;
import modelo.ConexionBD;
import modelo.Usuario;



/**
 *
 * @author erick
 */
public class MDIGimnasio extends javax.swing.JFrame {
    FRMIniciarSesion fIniciarSesion;
    FRMRegistrarse  fRegistrarse;
    

    /**
     * Creates new form MDIGimnasio
     */
    public MDIGimnasio() {
        ConexionBD.getInstance();
        initComponents();
        
        
        
        fIniciarSesion    = new FRMIniciarSesion(this);
        fRegistrarse      = new FRMRegistrarse();
        
        
        escritorio.add(fIniciarSesion);
        escritorio.add(fRegistrarse);
        
    }
    
    public javax.swing.JDesktopPane getEscritorio() {
    return escritorio;
}
    public void mostrarUsuario(Usuario usuario) {
        if(usuario == null){
            return;
        }

        FRMUsuario fUsuario = new FRMUsuario(usuario);

        escritorio.add(fUsuario);

        fUsuario.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new FondoEscritorio0();
        menuBar = new javax.swing.JMenuBar();
        MNUAdministrar = new javax.swing.JMenu();
        itemIniciarSeción = new javax.swing.JMenuItem();
        itemRegistrarse = new javax.swing.JMenuItem();
        itemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MNUAdministrar.setMnemonic('f');
        MNUAdministrar.setText("Administrar");

        itemIniciarSeción.setMnemonic('o');
        itemIniciarSeción.setText("Iniciar Sesión");
        itemIniciarSeción.addActionListener(this::itemIniciarSeciónActionPerformed);
        MNUAdministrar.add(itemIniciarSeción);

        itemRegistrarse.setText("Registrarse");
        itemRegistrarse.addActionListener(this::itemRegistrarseActionPerformed);
        MNUAdministrar.add(itemRegistrarse);

        itemSalir.setMnemonic('x');
        itemSalir.setText("Sallir");
        itemSalir.addActionListener(this::itemSalirActionPerformed);
        MNUAdministrar.add(itemSalir);

        menuBar.add(MNUAdministrar);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
        
        ConexionBD.desconectar();
        try {
            fIniciarSesion.setClosed(true);
            fRegistrarse.setClosed(true);
        } catch (PropertyVetoException ex) {
            System.err.println("Error al salir:"+ex.getMessage());
        }
        System.exit(0);
    }//GEN-LAST:event_itemSalirActionPerformed

    private void itemIniciarSeciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemIniciarSeciónActionPerformed
        // TODO add your handling code here:
        fIniciarSesion = new FRMIniciarSesion(this);

        escritorio.add(fIniciarSesion);
        
        fIniciarSesion.setVisible(true);
    }//GEN-LAST:event_itemIniciarSeciónActionPerformed

    private void itemRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistrarseActionPerformed
        // TODO add your handling code here:
        System.out.println("Abriendo registro... ");
        fRegistrarse = new FRMRegistrarse();

        escritorio.add(fRegistrarse);
        
        fRegistrarse.setVisible(true);
    }//GEN-LAST:event_itemRegistrarseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIGimnasio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIGimnasio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIGimnasio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIGimnasio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDIGimnasio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MNUAdministrar;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem itemIniciarSeción;
    private javax.swing.JMenuItem itemRegistrarse;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
